import { FormField, AutoGeneratedField } from "@/interfaces/cards";
import {
  generateCardNumber,
  generateExpiryDate,
  generateCardCompany,
} from "@/utils/cardUtils";

export const defaultAddCardFormFields: FormField[] = [
  {
    name: "cardHolder",
    label: "Card Holder Name",
    type: "text",
    placeholder: "Enter card holder name",
    required: true,
    validation: {
      minLength: 2,
      custom: (value) => {
        if (!value.trim()) return "Card holder name is required";
        if (value.trim().length < 2)
          return "Card holder name must be at least 2 characters";
        return undefined;
      },
    },
  },
  {
    name: "cardType",
    label: "Card Type",
    type: "select",
    required: true,
    options: [
      { value: "debit", label: "Debit Card" },
      { value: "credit", label: "Credit Card" },
    ],
  },
  {
    name: "initialBalance",
    label: "Initial Balance",
    type: "number",
    placeholder: "0.00",
    required: true,
    validation: {
      custom: (value) => {
        const balance = parseFloat(value);
        if (isNaN(balance) || balance < 0) {
          return "Please enter a valid positive number";
        }
        return undefined;
      },
    },
  },
];

export const defaultSpendLimitFormFields: FormField[] = [
  {
    name: "spendLimit",
    label: "Spend Limit",
    type: "number",
    placeholder: "0.00",
    required: true,
    validation: {
      custom: (value) => {
        const spendLimit = parseFloat(value);
        if (isNaN(spendLimit) || spendLimit < 0) {
          return "Please enter a valid positive number";
        }
        return undefined;
      },
    },
  },
]
export const defaultAddCardFormAutoGeneratedFields: AutoGeneratedField[] = [
  {
    name: "cardNumber",
    displayLabel: "Card Number",
    generateFunction: generateCardNumber,
  },
  {
    name: "expiry",
    displayLabel: "Expiry Date",
    generateFunction: generateExpiryDate,
  },
  {
    name: "cardCompany",
    displayLabel: "Card Company",
    generateFunction: generateCardCompany,
  },
];
