"use client";
import React, { useState, useEffect, useCallback, useMemo } from "react";
import {
  AddCardFormData,
  FormField,
  AutoGeneratedField as AutoGeneratedFieldType,
  CardCompany,
} from "@/interfaces/cards";
import FormFieldComponent from "./FormField";
import {
  defaultAddCardFormFields,
  defaultAddCardFormAutoGeneratedFields,
} from "@/constants/formConfigs";

interface AddCardModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSubmit: (
    data: Omit<AddCardFormData, "initialBalance"> & { initialBalance: number }
  ) => void;
  customFields?: FormField[];
  autoGeneratedFields?: AutoGeneratedFieldType[];
  'data-testid'?: string;
}

const AddCardModal: React.FC<AddCardModalProps> = ({
  isOpen,
  onClose,
  onSubmit,
  customFields = defaultAddCardFormFields,
  autoGeneratedFields = defaultAddCardFormAutoGeneratedFields,
  'data-testid': dataTestId,
}) => {
  const initializeFormData = useMemo(() => {
    const data: Record<string, string> = {};
    customFields.forEach((field) => {
      data[field.name] =
        field.type === "select" && field.options
          ? field.options[0]?.value || ""
          : "";
    });

    return data;
  }, [customFields]);

  const [formData, setFormData] =
    useState<Record<string, string>>(initializeFormData);
  const [errors, setErrors] = useState<Record<string, string>>({});

  const validateForm = useCallback(
    (formData: Record<string, string>): boolean => {
      const newErrors: Record<string, string> = {};

      customFields.forEach((field) => {
        const value = formData[field.name] || "";

        if (field.required && !value.trim()) {
          newErrors[field.name] = `${field.label} is required`;
          return;
        }

        if (field.validation) {
          const { minLength, maxLength, custom } = field.validation;

          if (minLength && value.length < minLength) {
            newErrors[
              field.name
            ] = `${field.label} must be at least ${minLength} characters`;
          }

          if (maxLength && value.length > maxLength) {
            newErrors[
              field.name
            ] = `${field.label} must be at most ${maxLength} characters`;
          }

          if (custom) {
            const customError = custom(value);
            if (customError) {
              newErrors[field.name] = customError;
            }
          }
        }
      });

      setErrors(newErrors);
      return Object.keys(newErrors).length === 0;
    },
    [customFields]
  );

  const generateAutoFields = useCallback(() => {
    const autoData: Record<string, string> = {};
    autoGeneratedFields.forEach((field) => {
      autoData[field.name] = field.generateFunction();
    });
    return autoData;
  }, [autoGeneratedFields]);

  const handleSubmit = useCallback(
    (e: React.FormEvent) => {
      // to avoid page reload
      e.preventDefault();
      if (validateForm(formData)) {
        const autoGeneratedData = generateAutoFields();
        const submitData = {
          cardHolder: formData.cardHolder || "",
          cardType: (formData.cardType as "debit" | "credit") || "debit",
          initialBalance: parseFloat(formData.initialBalance) || 0,
          cardNumber: autoGeneratedData.cardNumber,
          expiry: autoGeneratedData.expiry,
          cardCompany: autoGeneratedData.cardCompany as CardCompany,
        };

        onSubmit(submitData);
        onClose();
      }
    },
    [formData, validateForm, generateAutoFields, onSubmit, onClose]
  );

  const handleInputChange = useCallback(
    (fieldName: string, value: string) => {
      setFormData((prev) => ({ ...prev, [fieldName]: value }));
      if (errors[fieldName]) {
        setErrors((prev) => ({ ...prev, [fieldName]: "" }));
      }
    },
    [errors]
  );

  useEffect(() => {
    if (isOpen) {
      setFormData(initializeFormData);
      setErrors({});
    }
  }, [initializeFormData, isOpen]);

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4" data-testid={dataTestId}>
      <div className="bg-white rounded-xl p-6 w-full max-w-md max-h-[90vh] overflow-y-auto">
        <div className="flex justify-between items-center mb-6">
          <h2 className="text-xl font-semibold text-gray-800">Add New Card</h2>
          <button
            onClick={onClose}
            className="text-gray-400  transition-colors cursor-pointer"
            data-testid="close-modal"
          >
            <svg
              className="w-6 h-6"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M6 18L18 6M6 6l12 12"
              />
            </svg>
          </button>
        </div>

        <form onSubmit={handleSubmit} className="space-y-4">
          {/* Custom form fields only */}
          {customFields.map((field) => (
            <FormFieldComponent
              key={field.name}
              field={field}
              value={formData[field.name] || ""}
              error={errors[field.name]}
              onChange={(value) => handleInputChange(field.name, value)}
            />
          ))}

          <div className="flex space-x-3 pt-4">
            <button
              type="submit"
              className="flex-1 px-4 py-2 bg-highlight-blue text-white rounded-lg transition-colors cursor-pointer"
              data-testid="submit-card"
            >
              Add Card
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default AddCardModal;
