export interface CardDetails {
    cardNumber: string;
    cardHolder: string;
    expiry: string;
    type: string;
  }
  
 export interface Transaction {
    id: number;
    icon: string;
    iconColor: string;
    merchant: string;
    date: string;
    amount: string;
    color: string;
    info: string;
  }

export interface Card {
  id: string;
  cardNumber: string;
  cardHolder: string;
  expiry: string;
  cardCompany: CardCompany;
  isActive: boolean;
  isFrozen: boolean;
  balance: number;
  cardType: CardType;
}

export interface CardAction {
  id: string;
  name: string;
  icon: string;
  action: () => void;
}

export type CardType = 'debit' | 'credit';
export type CardCompany = 'visa' | 'mastercard';
export interface AddCardFormData {
  cardHolder: string;
  cardType: CardType;
  initialBalance: string;
  cardNumber: string;
  expiry: string;
  cardCompany: CardCompany;
}

export interface SpendLimitFormData {
  spendLimit: number;
  cardNumber: string;
}

// New interfaces for modular form system
export interface FormField {
  name: string;
  label: string;
  type: 'text' | 'number' | 'select' | 'email' | 'tel';
  placeholder?: string;
  required?: boolean;
  validation?: {
    minLength?: number;
    maxLength?: number;
    pattern?: string;
    custom?: (value: string) => string | undefined;
  };
  options?: Array<{ value: string; label: string }>;
  autoGenerate?: boolean;
  autoGenerateFunction?: () => string;
}

export interface AutoGeneratedField {
  name: string;
  generateFunction: () => string;
  displayLabel?: string;
}